### ISSUE TITLE
Global Styles SCSS Wishlist

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/guide-to-github#1]
I'm sure this is probably the wrong place, but when there's time, I'd love to have a nice way to handle fractions. Or, I'd love to never have to write the css for this again.  
<span class="fraction"><sup>3</sup><span>/</span><sub>16</sub></span>

**Comment by ivanreese** [comment]
`&frasl;`

like `5&frasl;6`

**Comment by ivanreese** [comment]
Moved to cdig/imagineering/#2
